project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_API_TOKEN
preserve_hierarchy: true
files:
  - source: /src/locales/en/messages.json
    dest: /src/locales/en/%file_name%.%file_extension%
    translation: /src/locales/%two_letters_code%/%original_file_name%
    update_option: update_as_unapproved
    languages_mapping:
      two_letters_code:
        pt-PT: pt_PT
        pt-BR: pt_BR
        zh-CN: zh_CN
        zh-TW: zh_TW
        en-GB: en_GB
        en-IN: en_IN
        sr-CY: sr_CY
        sr-CS: sr_CS
