project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_API_TOKEN
preserve_hierarchy: true
files:
  - source: /src/_locales/en/messages.json
    dest: /src/_locales/en/%original_file_name%
    translation: /src/_locales/%two_letters_code%/%original_file_name%
    update_option: update_as_unapproved
    languages_mapping:
      two_letters_code:
        pt-PT: pt_PT
        pt-BR: pt_BR
        zh-CN: zh_CN
        zh-TW: zh_TW
        en-GB: en_GB
        en-IN: en_IN
  - source: /store/locales/en/copy.resx
    dest: /store/locales/en/%original_file_name%
    translation: /store/locales/%two_letters_code%/%original_file_name%
    update_option: update_as_unapproved
    languages_mapping:
      two_letters_code:
        pt-PT: pt_PT
        pt-BR: pt_BR
        zh-CN: zh_CN
        zh-TW: zh_TW
        en-GB: en_GB
        en-IN: en_IN
