name: bw
version: __version__
summary: Bitwarden CLI - A secure and free password manager for all of your devices.
description: |
  Bitwarden, Inc. is the parent company of 8bit Solutions LLC.

  NAMED BEST PASSWORD MANAGER BY THE VERGE, U.S. NEWS &amp; WORLD REPORT, CNET, AND MORE.
      
  Manage, store, secure, and share unlimited passwords across unlimited devices from anywhere. Bitwarden delivers open source password management solutions to everyone, whether at  home, at work, or on the go.
      
  Generate strong, unique, and random passwords based on security requirements for every website you frequent.
      
  Bitwarden Send quickly transmits encrypted information --- files and plaintext -- directly to anyone.
      
  Bitwarden offers Teams and Enterprise plans for companies so you can securely share passwords with colleagues.
      
  Why Choose Bitwarden:
      
  World-Class Encryption
  Passwords are protected with advanced end-to-end encryption (AES-256 bit, salted hashing, and PBKDF2 SHA-256) so your data stays secure and private.
      
  Built-in Password Generator
  Generate strong, unique, and random passwords based on security requirements for every website you frequent.
      
  Global Translations 
  Bitwarden translations exist in 40 languages and are growing, thanks to our global community.
      
  Cross-Platform Applications
  Secure and share sensitive data within your Bitwarden Vault from any browser, mobile device, or desktop OS, and more.
confinement: strict
base: core18
apps:
  bw:
    command: bw
    environment:
      XDG_CONFIG_HOME: $SNAP_USER_DATA
    plugs: [network, network-bind]
parts:
  bw:
    plugin: dump
    source: ./bw-linux-$SNAPCRAFT_PROJECT_VERSION.zip
    override-build: |
      chmod +x bw
      snapcraftctl build
